quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=objektno
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/car_rental_db


#quarkus.hibernate-orm.database.generation=drop-and-create


quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true

quarkus.hibernate-orm.dev-ui.sql-load-script-is-optional=true
quarkus.scheduler.enabled=true


quarkus.http.port=8081


quarkus.oidc.auth-server-url=http://localhost:8081/realms/car_rental_db
quarkus.oidc.client-id=rentacar-backend
quarkus.oidc.credentials.secret=WWTrnbuYVJnf6UocM0OlMKrCpI4UJzvF


#quarkus.http.auth.permission.authenticated.paths=/*
#quarkus.http.auth.permission.authenticated.policy=authenticated