
quarkus.datasource.db-kind=postgresql


quarkus.datasource.username=postgres


quarkus.datasource.password=objektno


quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/car_rental_db


quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true